// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package button

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF248ab8DecodeGithubComMike7109TgBotClubbingInternalTransportWorkerUpdateEntityButton(in *jlexer.Lexer, out *Button) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "d":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Data = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 interface{}
					if m, ok := v1.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v1.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v1 = in.Interface()
					}
					(out.Data)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "c":
			out.Command = Command(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF248ab8EncodeGithubComMike7109TgBotClubbingInternalTransportWorkerUpdateEntityButton(out *jwriter.Writer, in Button) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"d\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Data == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Data {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if m, ok := v2Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v2Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v2Value))
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"c\":"
		out.RawString(prefix)
		out.String(string(in.Command))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Button) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF248ab8EncodeGithubComMike7109TgBotClubbingInternalTransportWorkerUpdateEntityButton(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Button) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF248ab8EncodeGithubComMike7109TgBotClubbingInternalTransportWorkerUpdateEntityButton(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Button) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF248ab8DecodeGithubComMike7109TgBotClubbingInternalTransportWorkerUpdateEntityButton(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Button) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF248ab8DecodeGithubComMike7109TgBotClubbingInternalTransportWorkerUpdateEntityButton(l, v)
}
