name:  Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - 
      name: Extract repository name and organization
      run: |
        GITHUBORG=$(echo "${GITHUB_REPOSITORY%%/*}" | tr "[:upper:]" "[:lower:]")
        echo "GITHUBORG=${GITHUBORG}" >> $GITHUB_ENV
        echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    -
      name: Build and push HTTP Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
            ghcr.io/${{ env.GITHUBORG }}/${{ env.REPO_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME_HOSTS }}@${{ secrets.IP_HOSTS }} "bash ./deploy.sh"